import { readFileSync, appendFileSync } from "node:fs";

import { rollup, toMarkdown, type Bucket, type OtlpExport, type RollupReport } from "./rollup.js";

export interface RunnerEnv {
  /** GitHub Actions inputs prefixed with INPUT_ (uppercase, dashes replaced by underscores). */
  inputs: Record<string, string | undefined>;
  /** GitHub Actions context paths. */
  GITHUB_OUTPUT?: string;
  GITHUB_EVENT_NAME?: string;
  GITHUB_REPOSITORY?: string;
  GITHUB_EVENT_PATH?: string;
  /** Where to read the OTLP/JSON from (defaults to fs). */
  readFile?: (path: string) => string;
  /** Posts a PR comment via GitHub API. Stubbed for tests. */
  postComment?: (args: { token: string; repo: string; issueNumber: number; body: string }) => Promise<void>;
  /** Stream to write output annotations (defaults to process.stdout). */
  write?: (line: string) => void;
}

export interface RunnerResult {
  exitCode: 0 | 1;
  report: RollupReport;
  commentPosted: boolean;
  reason?: string;
}

const BUCKETS: Bucket[] = ["day", "month", "all"];

export async function run(env: RunnerEnv): Promise<RunnerResult> {
  const input = required(env.inputs, "input");
  const bucket = optionalEnum<Bucket>(env.inputs, "bucket", "day", BUCKETS);
  const commentOnPr = env.inputs.comment_on_pr ?? "auto";
  const failOverRaw = env.inputs.fail_over_usd;
  const failOverUsd = failOverRaw && failOverRaw.length > 0 ? Number(failOverRaw) : undefined;
  if (failOverUsd !== undefined && (!Number.isFinite(failOverUsd) || failOverUsd < 0)) {
    throw new Error(`fail-over-usd must be a non-negative number; got "${failOverRaw}"`);
  }
  const token = env.inputs.github_token ?? "";

  const read = env.readFile ?? ((p) => readFileSync(p, "utf8"));
  const write = env.write ?? ((line) => process.stdout.write(`${line}\n`));

  const payload = JSON.parse(read(input)) as OtlpExport;
  const report = rollup(payload, bucket);
  const markdown = toMarkdown(report);

  setOutput(env, "spans", String(report.totals.spans));
  setOutput(env, "total-cost-usd", report.totals.costUSD.toFixed(4));
  setOutput(env, "rows", JSON.stringify(report.rows));

  write(`\n${markdown}\n`);

  // Decide PR commenting
  const isPullRequest = env.GITHUB_EVENT_NAME === "pull_request";
  const wantsComment = commentOnPr === "true" || (commentOnPr === "auto" && isPullRequest);
  let commentPosted = false;
  let reason: string | undefined;

  if (wantsComment) {
    if (!token) {
      reason = "no github-token provided";
    } else if (!env.GITHUB_EVENT_PATH) {
      reason = "no GITHUB_EVENT_PATH";
    } else if (!env.GITHUB_REPOSITORY) {
      reason = "no GITHUB_REPOSITORY";
    } else {
      const event = JSON.parse(read(env.GITHUB_EVENT_PATH)) as { number?: number; pull_request?: { number?: number } };
      const issueNumber = event.number ?? event.pull_request?.number;
      if (!issueNumber) {
        reason = "no PR number in event payload";
      } else {
        const body = `### LLM cost rollup\n\n${markdown}\n\n_Generated by [llm-cost-rollup-action](https://github.com/mizcausevic-dev/llm-cost-rollup-action)._`;
        const poster = env.postComment ?? defaultPostComment;
        await poster({ token, repo: env.GITHUB_REPOSITORY, issueNumber, body });
        commentPosted = true;
      }
    }
  }

  if (failOverUsd !== undefined && report.totals.costUSD > failOverUsd) {
    write(`::error::Total spend $${report.totals.costUSD.toFixed(4)} exceeds budget $${failOverUsd.toFixed(2)}.`);
    return { exitCode: 1, report, commentPosted, reason };
  }

  return { exitCode: 0, report, commentPosted, reason };
}

function required(inputs: Record<string, string | undefined>, name: string): string {
  const v = inputs[name];
  if (!v || v.length === 0) throw new Error(`input "${name}" is required`);
  return v;
}

function optionalEnum<T extends string>(
  inputs: Record<string, string | undefined>,
  name: string,
  def: T,
  allowed: readonly T[]
): T {
  const v = (inputs[name] ?? def) as T;
  if (!allowed.includes(v)) throw new Error(`input "${name}" must be one of: ${allowed.join(", ")}`);
  return v;
}

function setOutput(env: RunnerEnv, key: string, value: string): void {
  if (env.GITHUB_OUTPUT) appendFileSync(env.GITHUB_OUTPUT, `${key}=${value}\n`);
}

async function defaultPostComment(args: {
  token: string;
  repo: string;
  issueNumber: number;
  body: string;
}): Promise<void> {
  const r = await fetch(`https://api.github.com/repos/${args.repo}/issues/${args.issueNumber}/comments`, {
    method: "POST",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${args.token}`,
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({ body: args.body })
  });
  if (!r.ok) throw new Error(`GitHub API comment failed: ${r.status} ${await r.text()}`);
}
